<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\backend\EquilibraFitPlusPlus.Api\EquilibraFitPlusPlus.Api.csproj" />
    <ProjectReference Include="..\..\src\backend\EquilibraFitPlusPlus.Application\EquilibraFitPlusPlus.Application.csproj" />
    <ProjectReference Include="..\..\src\backend\EquilibraFitPlusPlus.Infrastructure\EquilibraFitPlusPlus.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\backend\EquilibraFitPlusPlus.Contracts\EquilibraFitPlusPlus.Contracts.csproj" />
    <ProjectReference Include="..\..\src\backend\EquilibraFitPlusPlus.Shared\EquilibraFitPlusPlus.Shared.csproj" />
  </ItemGroup>

</Project>
