<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>1251ecb6-88b7-4815-bc1f-312faedca0e6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\backend\EquilibraFitPlusPlus.Contracts\EquilibraFitPlusPlus.Contracts.csproj" />
    <ProjectReference Include="..\..\backend\EquilibraFitPlusPlus.Shared\EquilibraFitPlusPlus.Shared.csproj" />
  </ItemGroup>

</Project>
